apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
spec:
  selector:
    matchLabels:
      app: flagger
  template:
    metadata:
      labels:
        app: flagger
    spec:
      containers:
        - name: flagger
          args:
            - -log-level=info
            - -mesh-provider=nginx
            - -metrics-server=http://flagger-prometheus:9090